import { ExternalLinkIcon } from "@/assets/images";
import Image from "next/image";


const openExternalLink = (url: string | undefined) => {
    if (url) {
        const safeUrl = url.startsWith('http://') || url.startsWith('https://') ? url : `https://${url}`;
        window.open(safeUrl, '_blank');
    }
};

const ExternalLink = () => (
    <Image src={ExternalLinkIcon} alt="External Link Icon" width={16} height={16} />
);

function ExternalLinkItem({ title, url }: { title: string, url: string | undefined }) {
    if (!url) {
        return (
            <div className="flex flex-col pt-4 pb-4 px-6 bg-[#1A1616]/40 rounded-[4px] min-h-[70px]">
                <h4 className="text-[12px] text-white/40 mb-1">{title}</h4>
                <div className="flex items-center text-[14px] text-white/64">N/A</div>
            </div>
        );
    }

    // New logic: Wrap the text and icon in an anchor tag for reliability
    // The anchor tag uses the safer link generated by openExternalLink for its href
    const safeUrl = url.startsWith('http://') || url.startsWith('https://') ? url : `https://${url}`;

    return (
        <div className="flex flex-col pt-4 pb-4 px-6 bg-[#1A1616]/40 rounded-[4px] min-h-[70px]">
            <h4 className="text-[12px] text-white/40 mb-1">{title}</h4>

            <a
                href={safeUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center text-[14px] text-white/64 cursor-pointer transition-opacity hover:opacity-80"
                title={`Open ${title}`}
            >
                {/* Display the link text */}
                {url}

                {/* External Link Icon */}
                <div className="inline-flex ml-2 text-white/64">
                    <ExternalLink />
                </div>
            </a>
        </div>
    );
}

export default function ExternalLinksTab({ formData }: { formData: any }) {
    return (
        <div className="grid gap-4 mt-[40px] mb-[64px] w-[900px]">

            <div className="grid gap-4 mt-[40px] mb-[64px] w-[900px]">

                {/* Card 1: GitHub Repository */}
                <ExternalLinkItem
                    title="GitHub Repository"
                    url={formData.github}
                />

                {/* Card 2: Dataset */}
                <ExternalLinkItem
                    title="Dataset"
                    url={formData.dataset}
                />

                {/* Card 3: Supplementary Materials */}
                <ExternalLinkItem
                    title="Supplementary Materials"
                    url={formData.supplementaryMaterials}
                />
            </div>
        </div>
                
    )
}